FROM registry.access.redhat.com/ubi10:latest
LABEL org.opencontainers.image.authors="Gergely Lonyai"
LABEL org.opencontainers.image.source=https://github.com/fjordos/pods
LABEL org.opencontainers.image.description="Simple Caddy image"
LABEL org.opencontainers.image.licenses=GPL-3.0-or-later

RUN curl https://go.dev/dl/go1.26.1.linux-amd64.tar.gz | tar xzf -
RUN dnf copr enable -y @caddy/caddy && dnf upgrade -y && dnf install -y caddy && dnf clean all
RUN go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
EXPOSE 80 443 443/udp

#ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile"]
