FROM registry.access.redhat.com/ubi10:latest as build

RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-10.noarch.rpm https://rpms.remirepo.net/enterprise/remi-release-10.rpm
RUN yum config-manager --set-enabled codeready-builder-for-rhel-10-x86_64-rpms --set-enabled rhel-10-for-x86_64-appstream-rhui-rpms --set-enabled remi 
RUN crb status | grep enabled || crb enable
RUN yum upgrade -y && yum groupinstall -y "RPM Development Tools" "Development Tools"

WORKDIR /root
COPY fake-filesystem-unmerged-sbin-symlinks.spec fake-filesystem-unmerged-sbin-symlinks.spec
RUN rpmbuild -bb fake-filesystem-unmerged-sbin-symlinks.spec && yum install -y /root/rpmbuild/RPMS/x86_64/fake-filesystem-unmerged-sbin-symlinks-1-1.el10.x86_64.rpm
COPY rpms rpms
RUN yum install -y ./rpms/*.rpm && yum install -y uw-imap-devel aspell-devel bzip2-devel curl-devel cyrus-sasl-devel enchant-devel freetds-devel gd-devel gdbm-devel gmp-devel httpd-devel krb5-devel libacl-devel libdb-devel libedit-devel libicu-devel libtidy-devel libtool-ltdl-devel libxml2-devel libxslt-devel net-snmp-devel openldap-devel openssl-devel pam-devel pcre2-devel perl postgresql-devel recode-devel smtpdaemon sqlite-devel systemd-devel tokyocabinet-devel unixODBC-devel
# systemtap-sdt-devel
COPY ./php-5.6.40-*.src.rpm .
RUN rpmbuild --rebuild --without=db4-devel --without=oci8 ./php-5.6.40-*.src.rpm --nodeps

aspell-devel bzip2-devel curl-devel cyrus-sasl-devel enchant-devel freetds-devel gd-devel gdbm-devel gmp-devel httpd-devel krb5-devel libacl-devel libdb-devel libedit-devel libicu-devel libtidy-devel libtool-ltdl-devel libxslt-devel net-snmp-devel openldap-devel pam-devel pcre-devel perl postgresql-devel recode-devel smtpdaemon sqlite-devel systemd-devel tokyocabinet-devel unixODBC-devel

#

FROM registry.access.redhat.com/ubi10/httpd-24

LABEL org.opencontainers.image.authors="Gergely Lonyai"
LABEL org.opencontainers.image.source=https://github.com/fjordos/pods
LABEL org.opencontainers.image.description="Simple HTTPd with PHP-5.6 image for historical webapp"
LABEL org.opencontainers.image.licenses=GPL-3.0-or-later

COPY --from=build /tmp /tmp
